export const GET_CRYPTO_VALUES = 'GET_CRYPTO_VALUES';
export const SET_CRYPTO_PAGE = 'SET_CRYPTO_PAGE';
export const CLEAR_CRYPTO_VALUES = 'CLEAR_CRYPTO_VALUES';
export const SORT_CRYPTO_VALUES = 'SORT_CRYPTO_VALUES';